version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=recipe_book_db
    ports:
      - '5433:5432'
    volumes:
      - type: volume
        source: recipe-db
        target: /var/lib/postgresql/data
      - type: bind
        source: ./db/init-recipes.sql
        target: /docker-entrypoint-initdb.d/create_tables.sql
volumes:
  recipe-db:
    driver: local